import {
  Briefcase,
  Building2,
  Search,
  Code2,
  GraduationCap,
  PhoneCall,
  Coffee,
  Tv,
  ClipboardList,
  Footprints,
  Droplets,
  Sparkles,
  Bath,
  Moon,
  HelpCircle,
  Zap,
  Target,
  Heart,
  Music,
  Dumbbell,
  Utensils,
  Car,
  Home,
  Users,
  Star,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "job 1": Briefcase,
  "job 2": Building2,
  "client hunting": Search,
  "agency project development": Code2,
  "skill learning": GraduationCap,
  "lead follow-up": PhoneCall,
  break: Coffee,
  entertainment: Tv,
  "regular tasks": ClipboardList,
  walking: Footprints,
  bathing: Droplets,
  brushing: Sparkles,
  toilet: Bath,
  sleep: Moon,
  other: HelpCircle,
  focus: Zap,
  goals: Target,
  health: Heart,
  music: Music,
  exercise: Dumbbell,
  food: Utensils,
  commute: Car,
  home: Home,
  meetings: Users,
  priority: Star,
};

export function getCategoryIcon(categoryName: string): LucideIcon {
  return ICON_MAP[categoryName.toLowerCase()] || HelpCircle;
}
